mode: "Photo"
mask: "/1T/Results/data/masks/1586379826470 60.png"
detections: "/1T/Results/data/labels/1586379826470 60.txt"
save_path: "/1T/Results/data/results/1586379826470 60(2).jpg"

size: [480, 270]

y_limits: [0.0, 1]
start: [0.7, 1.0]
not_path_point: [0, 0, 0]

show: True
ratio: 1
radius: 2
thickness: 2



  